version: '3.1'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef

    ports:
      - '5432:5432'